### ISSUE TITLE
Where are files

### ISSUE THREAD

**Issue by TymianekPL** [archuser555/mlcpu#1]
Where is source code

**Comment by archuser555** [comment]
Ummm, you can just... this is a CPU MY FREIND, THE SOURCE CODE IS OF COURSE CIRCUITS AND SHIT, also, im working on a basic website for this project, you can help if you want
About your question, the cpu aren't completed, dont wait complexe things, big stuffs start small XD

**Comment by archuser555** [comment]
@TymianekPL
